{"name": "Логин с неверным логином и паролем", "status": "passed", "description": "Проверка логина с неверным email и паролем. Тест проверяет, что возвращается ошибка 401 с соответствующим сообщением.", "start": 1725538048431, "stop": 1725538048728, "uuid": "3ff340a3-82ee-4f80-bb83-a9dfaedc42f3", "historyId": "5c57ed1aabe4ade7b4ea9aadb604b2ea", "testCaseId": "5c57ed1aabe4ade7b4ea9aadb604b2ea", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_incorrect_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "14412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}