{"name": "Логин с неверным логином и паролем", "status": "passed", "description": "Проверка логина с неверным email и паролем. Тест проверяет, что возвращается ошибка 401 с соответствующим сообщением.", "start": 1726233882457, "stop": 1726233882697, "uuid": "ed9a4aa7-9032-4f16-a2c2-489c3639a82d", "historyId": "5c57ed1aabe4ade7b4ea9aadb604b2ea", "testCaseId": "5c57ed1aabe4ade7b4ea9aadb604b2ea", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_incorrect_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "12588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}